import dataaccessobjects.ConnectionProvider;
import dataaccessobjects.DivisionData;
import dataaccessobjects.EmployeeData;
import models.Division;
import models.Employee;

import java.math.BigDecimal;
import java.util.Date;
import java.util.Random;

public class DataAccessAgilityJavaSampleCode {
    public static void main(String[] args) {

        try {
            //Make sure to download and reference the MySql JDBC Driver
            Class.forName("com.mysql.cj.jdbc.Driver");

            //ConnectionProvider is a class that is auto generated by DataAccessAgility
            //Make sure to specify the database host, name, username, and password
            ConnectionProvider.setConnectionString("jdbc:mysql://DATABASE_HOST?allowMultiQueries=true", "db_username", "db_password");

            Random random = new Random(new Date().getTime());
            //
            //Add Division object to database
            //
            Division division = new Division();

            division.setId(random.nextInt(100000));
            division.setName("Sales");

            DivisionData.addDivision(division); //DivisionData is the data access object of Division table

            //
            //Add Employee object to database
            //
            Employee employee = new Employee();

            employee.setId(random.nextInt(100000));
            employee.setName("John Smith");
            employee.setHireDate(new Date());
            employee.setBaseSalary(new BigDecimal(1100.23));
            employee.setDivisionId(division.getId());

            EmployeeData.addEmployee(employee); //EmployeeData is the data access object of Employee table

            //
            //Get Employee object from database
            //
            Employee storedEmployee = EmployeeData.getEmployeeById(employee.getId());

            System.out.println("******* Employee Card *******");
            System.out.println(storedEmployee.getId());
            System.out.println(storedEmployee.getName());
            System.out.println(storedEmployee.getHireDate());
            System.out.println(storedEmployee.getBaseSalary());
            System.out.println("******* Employee Card End *******");
        }
        catch (Exception ex) {
            System.out.println("Error: " + ex.getMessage());
            ex.printStackTrace();
        }
    }
}
